ITShop/Models/BaiViet.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ITShop.Models
{
    public class BaiViet
    {
        [DisplayName("Mã BV")]
        public int ID { get; set; }

        [DisplayName("Chủ đề")]
        [Required(ErrorMessage = "Chủ đề không được bỏ trống")]
        public int ChuDeID { get; set; }
        [DisplayName("Người đăng")]
        [Required(ErrorMessage = "Người đăng không được bỏ trống.")]

        public int NguoiDungID { get; set; }
        [StringLength(255)]
        [DisplayName("Tiêu đề")]
        [Required(ErrorMessage = "Tiêu đề không được bỏ trống")]
        public string TieuDe { get; set; }

        [StringLength(255)]
        [DisplayName("Tiêu đề không dấu")]
        public string? TieuDeKhongDau { get; set; }

        [Column(TypeName = "ntext")]
        [DisplayName("Tóm tắt bài viết")]
        [Required(ErrorMessage = "Tóm tắt bài viết không được bỏ trống.")]
        [DataType(DataType.MultilineText)]
        public string TomTat { get; set; }

        [Column(TypeName = "ntext")]
        [DisplayName("Nội dung")]
        [Required(ErrorMessage = "Nội dung bài viết không được bỏ trống.")]
        [DataType(DataType.MultilineText)]
        public string NoiDung { get; set; }

        [DisplayName("Ngày đăng")]
        [Required(ErrorMessage = "Ngày đăng không được bỏ trống.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime NgayDang { get; set; }

        [DisplayName("Lượt xem")]
        [DefaultValue(1)]
        public int LuotXem { get; set; }
        [DisplayName("Kiểm duyệt")]
        [DefaultValue(false)]
        public bool KiemDuyet { get; set; }
        [DisplayName("Hiển thị")]
        [DefaultValue(true)]
        public bool HienThi { get; set; }

        public ChuDe? ChuDe { get; set; }
        public NguoiDung? NguoiDung { get; set; }
        public ICollection<BinhLuanBaiViet>? BinhLuanBaiViet { get; set; }
    }

    [NotMapped]
    public class PhanTrangBaiViet
    {
        public int TrangHienTai { get; set; }
        public int TongSoTrang { get; set; }
        public List<BaiViet> BaiViet { get; set; }
        public bool HasPreviousPage => TrangHienTai > 1;
        public bool HasNextPage => TrangHienTai < TongSoTrang;
    }
}

ITShop/Models/ChuDe.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
namespace ITShop.Models
{
    public class ChuDe
    {
        [DisplayName("Mã chủ đề")]
        public int ID { get; set; }

        [StringLength(255)]
        [Required(ErrorMessage = "Tên chủ đề không được bỏ trống.")]
        [DisplayName("Tên chủ đề")]
        public string TenChuDe { get; set; }

        [StringLength(255)]
        [DisplayName("Tên chủ đề không dấu")]
        public string? TenChuDeKhongDau { get; set; }

        public ICollection<BaiViet>? BaiViet { get; set; }
    }
}

ITShop/Areas/Admin/Controllers/BaiVietController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SlugGenerator;
using ITShop.Models;
using Microsoft.AspNetCore.Authorization;
namespace ITShop.Areas.Admin.Controllers
{
 [Area("Admin")]
[Authorize(Roles = "Admin")]
public class BaiVietController : Controller
{
    private readonly ITShopDbContext _context;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public BaiVietController(ITShopDbContext context, IHttpContextAccessor httpContextAccessor)
    {
        _context = context;
        _httpContextAccessor = httpContextAccessor;
    }

    // GET: BaiViet
    public async Task<IActionResult> Index()
    {
        var iTShopDbContext = _context.BaiViet.Include(b => b.ChuDe).Include(b => b.NguoiDung).OrderByDescending(r => r.NgayDang);
        return View(await iTShopDbContext.ToListAsync());
    }

    // GET: BaiViet/Create
    public IActionResult Create()
    {
        ViewData["ChuDeID"] = new SelectList(_context.ChuDe, "ID", "TenChuDe");
        return View();
    }

    // POST: BaiViet/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("ID,ChuDeID,TieuDe,TieuDeKhongDau,TomTat,NoiDung,HienThi")] BaiViet baiViet)
    {
        if (ModelState.IsValid)
        {
            int maNguoiDung = Convert.ToInt32(_httpContextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "ID")?.Value);

            // Gán các giá trị mặc định
            baiViet.NguoiDungID = maNguoiDung;
            baiViet.NgayDang = DateTime.Now;
            baiViet.LuotXem = 0;
            baiViet.KiemDuyet = true;

            // Nếu tiêu đề không dấu bỏ trống thì tự động xử lý
            if (string.IsNullOrWhiteSpace(baiViet.TieuDeKhongDau))
            {
       
            baiViet.TieuDeKhongDau = baiViet.TieuDe.GenerateSlug();
            }

            _context.Add(baiViet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        ViewData["ChuDeID"] = new SelectList(_context.ChuDe, "ID", "TenChuDe", baiViet.ChuDeID);
        return View(baiViet);
    }

    // GET: BaiViet/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var baiViet = await _context.BaiViet.FindAsync(id);
        if (baiViet == null)
        {
            return NotFound();
        }
        ViewData["ChuDeID"] = new SelectList(_context.ChuDe, "ID", "TenChuDe", baiViet.ChuDeID);
        return View(baiViet);
    }

    // POST: BaiViet/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("ID,ChuDeID,TieuDe,TieuDeKhongDau,TomTat,NoiDung,KiemDuyet,HienThi")] BaiViet baiViet)
    {
        if (id != baiViet.ID)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                // Nếu tiêu đề không dấu bỏ trống thì tự động xử lý
                if (string.IsNullOrWhiteSpace(baiViet.TieuDeKhongDau))
                {
                    baiViet.TieuDeKhongDau = baiViet.TieuDe.GenerateSlug();
         
                }
                _context.Update(baiViet);
                // Bỏ qua không cập nhật
                _context.Entry(baiViet).Property(x => x.NguoiDungID).IsModified = false;
                _context.Entry(baiViet).Property(x => x.NgayDang).IsModified = false;
                _context.Entry(baiViet).Property(x => x.LuotXem).IsModified = false;
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BaiVietExists(baiViet.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["ChuDeID"] = new SelectList(_context.ChuDe, "ID", "TenChuDe", baiViet.ChuDeID);
        return View(baiViet);
    }

    // GET: BaiViet/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var baiViet = await _context.BaiViet
        .Include(b => b.ChuDe)
        .Include(b => b.NguoiDung)
        .FirstOrDefaultAsync(m => m.ID == id);
        if (baiViet == null)
        {
            return NotFound();
        }

        return View(baiViet);
       
    }

    // POST: BaiViet/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var baiViet = await _context.BaiViet.FindAsync(id);
        if (baiViet != null)
        {
            _context.BaiViet.Remove(baiViet);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool BaiVietExists(int id)
    {
        return _context.BaiViet.Any(e => e.ID == id);
    }
}
}

ITShop/Areas/Admin/Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITShop.Models;
using SlugGenerator;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace ITShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class ChuDeController : Controller
    {
        private readonly ITShopDbContext _context;

        public ChuDeController(ITShopDbContext context)
        {
            _context = context;
        }

        // GET: ChuDe
        public async Task<IActionResult> Index()
        {   
            return _context.ChuDe != null ?
                        View(await _context.ChuDe.ToListAsync()) :
                        Problem("Entity set 'ITShopDbContext.ChuDe'  is null.");
        }

        // GET: ChuDe/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ChuDe == null)
            {
                return NotFound();
            }

            var chuDe = await _context.ChuDe
                .FirstOrDefaultAsync(m => m.ID == id);
            if (chuDe == null)
            {
                return NotFound();
            }

            return View(chuDe);
        }

        // GET: ChuDe/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ChuDe/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,TenChuDe,TenChuDeKhongDau")] ChuDe chuDe)
        {
            if (ModelState.IsValid)
            {
				if (string.IsNullOrWhiteSpace(chuDe.TenChuDeKhongDau))
				{
					chuDe.TenChuDeKhongDau = chuDe.TenChuDe.GenerateSlug();
				}
				_context.Add(chuDe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chuDe);
        }

        // GET: ChuDe/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ChuDe == null)
            {
                return NotFound();
            }

            var chuDe = await _context.ChuDe.FindAsync(id);
            if (chuDe == null)
            {
                return NotFound();
            }
            return View(chuDe);
        }

        // POST: ChuDe/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,TenChuDe,TenChuDeKhongDau")] ChuDe chuDe)
        {
            if (id != chuDe.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
					if (string.IsNullOrWhiteSpace(chuDe.TenChuDeKhongDau))
					{
						chuDe.TenChuDeKhongDau = chuDe.TenChuDe.GenerateSlug();
					}

					_context.Update(chuDe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChuDeExists(chuDe.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chuDe);
        }

        // GET: ChuDe/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ChuDe == null)
            {
                return NotFound();
            }

            var chuDe = await _context.ChuDe
                .FirstOrDefaultAsync(m => m.ID == id);
            if (chuDe == null)
            {
                return NotFound();
            }

            return View(chuDe);
        }

        // POST: ChuDe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ChuDe == null)
            {
                return Problem("Entity set 'ITShopDbContext.ChuDe'  is null.");
            }
            var chuDe = await _context.ChuDe.FindAsync(id);
            if (chuDe != null)
            {
                _context.ChuDe.Remove(chuDe);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChuDeExists(int id)
        {
            return (_context.ChuDe?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

ITShop/Controllers/BaiVietController.cs
using ITShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace ITShop.Controllers
{
    public class BaiVietController : Controller
    {
        private readonly ITShopDbContext _context;
        private readonly HttpContext _httpContext = new HttpContextAccessor().HttpContext;
        public BaiVietController(ITShopDbContext context)
        {
            _context = context;
        }
        // GET: Index
        public IActionResult Index(int? trang)
        {
            var danhSach = LayDanhSachBaiViet(trang ?? 1);
            if (danhSach.BaiViet.Count == 0)
                return NotFound();
            else
                return View(danhSach);
        }
        private PhanTrangBaiViet LayDanhSachBaiViet(int trangHienTai)
        {
            int maxRows = 12;
            PhanTrangBaiViet phanTrang = new PhanTrangBaiViet();
            phanTrang.BaiViet = _context.BaiViet
            .Include(s => s.NguoiDung)
            .Include(s => s.ChuDe)
            .Where(r => r.KiemDuyet == true && r.HienThi == true)
            .OrderByDescending(r => r.NgayDang)
            .Skip((trangHienTai - 1) * maxRows)
            .Take(maxRows).ToList();
            decimal tongSoTrang = Convert.ToDecimal(_context.BaiViet.Count()) / Convert.ToDecimal(maxRows);
            phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
            phanTrang.TrangHienTai = trangHienTai;
            return phanTrang;
        }
        // GET: PhanLoai
        public IActionResult ChuDe(int? trang, string tenChuDe)
        {
            var danhSachPhanLoai = LayDanhSachBaiVietTheoChuDe(trang ?? 1, tenChuDe);
            if (danhSachPhanLoai.BaiViet.Count == 0)
                return NotFound();
            else
                return View(danhSachPhanLoai);
        }
        private PhanTrangBaiViet LayDanhSachBaiVietTheoChuDe(int trangHienTai, string tenChuDe)
        {
            int maxRows = 12;
            var baiVietTheoChuDe = _context.BaiViet
            .Include(s => s.NguoiDung)
            .Include(s => s.ChuDe)
            .Where(r => r.KiemDuyet == true && r.HienThi == true && r.ChuDe.TenChuDeKhongDau == tenChuDe);
            PhanTrangBaiViet phanTrang = new PhanTrangBaiViet();
            phanTrang.BaiViet = baiVietTheoChuDe.OrderByDescending(r => r.NgayDang)
            .Skip((trangHienTai - 1) * maxRows)
            .Take(maxRows).ToList();
            decimal tongSoTrang = Convert.ToDecimal(baiVietTheoChuDe.Count()) / Convert.ToDecimal(maxRows);
            phanTrang.TongSoTrang = (int)Math.Ceiling(tongSoTrang);
            phanTrang.TrangHienTai = trangHienTai;
            return phanTrang;
        }
        // GET: ChiTiet
        public IActionResult ChiTiet(string tieuDe)
        {
            var baiViet = _context.BaiViet
            .Include(s => s.NguoiDung)
            .Include(s => s.ChuDe)
            .Include(s => s.BinhLuanBaiViet)
            .Where(r => r.KiemDuyet == true && r.HienThi == true && r.TieuDeKhongDau == tieuDe).SingleOrDefault();
            if (baiViet == null)
                return NotFound();
            else
            {
                // Xử lý tăng lượt xem
                string _sessionKey = "DaXemBaiViet_" + baiViet.ID;
                if (string.IsNullOrEmpty(_httpContext.Session.GetString(_sessionKey)))
                {
                    baiViet.LuotXem = baiViet.LuotXem + 1;
                    _context.Update(baiViet);
                    _context.SaveChanges();
                    _httpContext.Session.SetString(_sessionKey, "1");
                }
                // Lấy bài viết cùng chuyên mục
                var baiVietCungChuyenMuc = _context.BaiViet
                    .Include(s => s.NguoiDung)
                    .Include(s => s.ChuDe)
                    .Where(r => r.KiemDuyet == true && r.HienThi == true && r.ChuDeID == baiViet.ChuDeID && r.ID != baiViet.ID)
                    .OrderByDescending(r => r.NgayDang)
                    .Take(4);
                ViewData["BaiVietCungChuyenMuc"] = baiVietCungChuyenMuc;

                return View(baiViet);
            }
        }
    }
}

ITShop/Views/BaiViet/ChiTiet.cshtml
@model ITShop.Models.BaiViet
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor;
@using System.Text.RegularExpressions
@{
    ViewData["Title"] = Model.TieuDe;
    var baiVietCungChuyenMuc = ViewData["BaiVietCungChuyenMuc"] as IEnumerable<ITShop.Models.BaiViet>;
}
<div class="bg-secondary py-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
        <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb flex-lg-nowrap justify-content-center justify-content-lg-start">
                    <li class="breadcrumb-item">
                        <a class="text-nowrap" asp-area="" asp-controller="Home" asp-action="Index"><i class="ci-home"></i>Trang chủ</a>
                    </li>
                    <li class="breadcrumb-item text-nowrap">
                        <a asp-area="" asp-controller="BaiViet" asp-action="Index">Tin tức</a>
                    </li>
                    <li class="breadcrumb-item text-nowrap active" aria-current="page">Chi tiết</li>
                </ol>
            </nav>
        </div>
        <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
            <h1 class="h3 mb-0">@ViewData["Title"]</h1>
        </div>
    </div>
</div>
<div class="container pb-5">
    <div class="row justify-content-center pt-3 mt-md-3">
        <div class="col-12">
            <div class="d-flex flex-wrap justify-content-between align-items-center pb-4 mt-n1">
                <div class="d-flex align-items-center fs-sm mb-2">
                    <a class="blog-entry-meta-link" href="#author">
                        <div class="blog-entry-author-ava">
                            <img src="~/img/03.jpg" />
                        </div>
                        @Model.NguoiDung.HoVaTen
                    </a>
                    <span class="blog-entry-meta-divider"></span>
                    <a class="blog-entry-meta-link" href="#date">@Model.NgayDang</a>
                </div>
                <div class="fs-sm mb-2">
                    <a class="blog-entry-meta-link text-nowrap" href="#views" data-scroll>
                        <i class="ci-eye"></i>@Model.LuotXem
                    </a>
                </div>
            </div>
            <p style="text-align:justify">@Model.TomTat</p>
            <p style="text-align:justify">@Html.Raw(Model.NoiDung)</p>
            <div class="d-flex flex-wrap justify-content-between pt-2 pb-4 mb-1">
                <div class="mt-3 me-3">
                    <a class="btn-tag mb-2" href="#">#@Model.ChuDe.TenChuDeKhongDau</a>
                </div>
                <div class="mt-3">
                    <span class="d-inline-block align-middle text-muted fs-sm me-3 mt-1 mb-2">Chia sẻ bài viết:</span>
                    <a class="btn-social bs-facebook me-2 mb-2" href="#"><i class="ci-facebook"></i></a>
                    <a class="btn-social bs-twitter me-2 mb-2" href="#"><i class="ci-twitter"></i></a>
                    <a class="btn-social bs-pinterest me-2 mb-2" href="#"><i class="ci-pinterest"></i></a>
                </div>
            </div>
            <div class="pt-2 mt-2" id="comments">
                <h2 class="h4">Bình luận<span class="badge bg-secondary fs-sm text-body align-middle ms-2">@Model.BinhLuanBaiViet.Count()</span></h2>
                @foreach (var binhLuan in Model.BinhLuanBaiViet)
                {
                <div class="d-flex align-items-start py-4">
                        <img class="rounded-circle" src="~/img/03.jpg" width="50" />
                        <div class="ps-3">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <h6 class="fs-md mb-0">@binhLuan.NguoiDung.HoVaTen</h6>
                            </div>
                            <p class="fs-md mb-1" style="text-align:justify">@binhLuan.NoiDungBinhLuan</p>
                            <span class="fs-ms text-muted"><i class="ci-time align-middle me-2"></i>@binhLuan.NgayDang</span>
                        </div>
                    </div>
                }
                <div class="card border-0 shadow mt-2 mb-4">
                    <div class="card-body">
                        <div class="d-flex align-items-start">
                            <img class="rounded-circle" src="~/img/03.jpg" width="50" />
                            <form class="w-100 needs-validation ms-3" novalidate>
                                <div class="mb-3">
                                <textarea class="form-control" rows="3" placeholder="Chia sẻ ý kiến của bạn..." required></textarea>
                                    @if (!_httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                                    {
                                        <div class="invalid-feedback">Vui lòng đăng nhập để gởi bình luận.</div>
                                    }
                                    else
                                    {
                                        <div class="invalid-feedback">Nội dung bình luận không được bỏ trống.</div>
                                    }
                                </div>
                                <button class="btn btn-primary btn-sm" type="submit">Đăng bình luận</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@if (baiVietCungChuyenMuc.Count() > 0)
{
    <div class="bg-secondary py-5">
        <div class="container py-3">
            <h2 class="h4 text-center pb-4">Bài viết cùng chuyên mục</h2>
            <div class="tns-carousel">
                <div class="tns-carousel-inner" data-carousel-options="{&quot;items&quot;: 2, &quot;controls&quot;: false, &quot;autoHeight&quot;: true, &quot;responsive&quot;: {&quot;0&quot;:{&quot;items&quot;:1},&quot;500&quot;:{&quot;items&quot;:2, &quot;gutter&quot;: 20},&quot;900&quot;:{&quot;items&quot;:3, &quot;gutter&quot;: 20}, &quot;1100&quot;:{&quot;items&quot;:3, &quot;gutter&quot;: 30}}}">
                    @foreach (var item in baiVietCungChuyenMuc)
                    {
                        <article>
                            @{
                                string hinhAnhDauTien = Regex.Match(item.NoiDung, "<img.+?src=[\"'](.+?)[\"'].*?>", RegexOptions.IgnoreCase).Groups[1].Value.Replace("&amp;", "&");
                                if (string.IsNullOrEmpty(hinhAnhDauTien)) hinhAnhDauTien = "/img/noimage.png";
                            }
                            <a class="blog-entry-thumb mb-3" asp-area="" asp-controller="BaiViet" asp-action="ChiTiet" asp-route-tieuDe="@item.TieuDeKhongDau">
                                <img src="@hinhAnhDauTien" />
                            </a>
                            <div class="d-flex align-items-center fs-sm mb-2">
                                <a class="blog-entry-meta-link" href="#author">bởi @item.NguoiDung.HoVaTen</a>
                                <span class="blog-entry-meta-divider"></span>
                                <a class="blog-entry-meta-link" href="#date">@item.NgayDang</a>
                            </div>
                            <h3 class="h6 blog-entry-title">
                                <a asp-area="" asp-controller="BaiViet" asp-action="ChiTiet" asp-route-tieuDe="@item.TieuDeKhongDau">
                                    @item.TieuDe
                                </a>
                            </h3>
                        </article>
                    }
                </div>
            </div>
        </div>
    </div>
}